name: assets_audio_player_plus
description: Play music/audio stored in assets files directly from Flutter & Network, Radio, LiveStream, Local files. Compatible with Android, iOS, and macOS.
version: 3.2.0

#author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/cyclone-pk/assets_audio_player_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  uuid: ^4.5.3
  http: ^1.6.0
  path_provider: ^2.1.5
  assets_audio_player_plus_web: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  assets_audio_player_plus_web:
    path: ./assets_audio_player_plus_web

flutter:
  plugin:
    platforms:
      android:
        package: com.github.florent37.assets_audio_player
        pluginClass: AssetsAudioPlayerPlugin
        mainClass: AssetsAudioPlayerPlugin
      ios:
        pluginClass: AssetsAudioPlayerPlugin
      macos:
        pluginClass: AssetsAudioPlayerPlugin
      web:
        default_package: assets_audio_player_plus_web
